AWSTemplateFormatVersion: '2010-09-09'
Description: Create an ECR repo with S3 buckets and IAM roles + policy 

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - staging
      - prod

  BuildNumber:
    Type: String
    Default: "1"
    Description: The CI/CD build number for tagging. 
  

Resources:
  ECRInstance:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${EnvironmentName}/wk2-myapp"
      ImageScanningConfiguration: 
        ScanOnPush: true
      # ImageTagMutability: IMMUTABLE_WITH_EXCLUSION
      # ImageTagMutabilityExclusionFilters: 
      #   - ImageTagMutabilityExclusionFilterType: WILDCARD
      #     ImageTagMutabilityExclusionFilterValue: "test"
      ImageTagMutability: IMMUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": { "type": "expire" }
              }
            ]
          }
      Tags: 
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: BuildVersion
          Value: !Ref BuildNumber


  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${EnvironmentName}-wk2-bucket-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # IAM Role with Trust Policy
  MyAppRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: !Sub "${EnvironmentName}-myapp-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect : Allow 
            Principal: 
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      # ManagedPolicyArns: 
      #   - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
  # Inline Policy for specific S3 and ECR Write access
      Policies:
        - PolicyName: !Sub "${EnvironmentName}-ResourceAccessPolicy"
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
              - Sid: S3WriteAccess
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource: 
                  - !GetAtt S3Bucket.Arn
                  - !Sub "${S3Bucket.Arn}/*"
              - Sid: ECRPushAccess
                Effect: Allow
                Action:
                  - ecr:PutImage
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchCheckLayerAvailability
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:InitiateLayerUpload
                Resource: !GetAtt ECRInstance.Arn

Outputs:
  ECRRepositoryURI:
    Description: "The URI of the ECR repository to be used in docker push/pull commands"
    Value: !GetAtt ECRInstance.RepositoryUri
    Export:
      Name: !Sub "${AWS::StackName}-ECR-URI"
  
  S3BucketName:
    Description: S3 Bucket Name
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-S3-Bucket"
  
  MyAppRoleARN:
    Description: "The ARN of the IAM Role for application permissions"
    Value: !GetAtt MyAppRole.Arn
    Export: 
      Name: !Sub "${AWS::StackName}-Role-ARN"